/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fp.practice;
import java.math.BigDecimal;

public class App {

    public static void main(String[] args) {
        FpConfig cp =  new FpConfig();
        BigDecimal result1 = cp.calculateConfig().apply(new BigDecimal(100));

        System.out.println("计算结果：");
        System.out.println(result1);
    }

}
